# ref: https://flake8.pycqa.org/en/latest/user/options.html
[flake8]
count = True
statistics = True
max-complexity = 10
max-line-length = 200

# ref: https://flake8.pycqa.org/en/latest/user/error-codes.html
# E201 + E202 : whitespace after "(" or before ")"
# E127 + E128 : continuation line over or under-indented for visual indent
# E222: multiple spaces after operator
# E251: unexpected spaces around keyword / parameter equals
# E303: too many blank lines (shouldn't be ignored)
# E702: multiple statements on one line with a semicolon
extend-ignore=E201,E202,E127,E128,E222,E251,E303,E702