{
 "title": "device: freebox (fibre) - git",
 "description": "Dashboard pour Freebox (Fibre) - API v4+",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dsdashboard", "label": "Datasource name", "query": "influxdb" },
   { "name": "dsinterval", "label": "Datasource Interval", "query": "5m" },
   {
    "name": "server",
    "label": "Server:",
    "query": "SHOW TAG values FROM \"freebox\" with key = \"host\""
   },
   {
    "name": "switch",
    "label": "Lan switch",
    "query": "SHOW TAG values FROM \"freebox_switch\" with key = \"switch_port\" where \"host\" = '$server'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;font-size:1.3em\" >\n  Domain ${__org.name}\n  <hr style=\"background-image:linear-gradient(to right, goldenrod, firebrick);height:1px;border:0; margin:auto 42%\" />\n  Device Freebox : $server\n</div>"
   }
  },
  {
   "title": "Availability history - $server",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Box" ], "type": "alias" }
      ],
      [
       { "params": [ "sfp_has_signal" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "WAN " ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime: $server",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Download - current: WAN (Bytes/s)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate_down" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Upload - current: WAN (Bytes/s)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate_up" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "firmware_version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime: WAN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sfp_has_signal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "$server - WAN informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sys_uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sfp_has_signal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "sfp_uptime" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN IPv4 address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "wan_ipv4" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "IPv4 port range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "alias": "$col",
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "wan_ipv4_port_range_min" ], "type": "field" },
       { "params": [ "Min" ], "type": "alias" }
      ],
      [
       { "params": [ "wan_ipv4_port_range_max" ], "type": "field" },
       { "params": [ "Max" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "hw_model" ], "type": "tag" }
     ],
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "firmware_version" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "WAN IPv6 address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "wan_ipv6" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "API version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "api_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sys_uptime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "MAC address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "hw_mac" ], "type": "tag" }
     ],
     "limit": "3",
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "firmware_version" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "$server - Recap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "System sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_sensor ($tag_sensor_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "sensor_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sys_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "temp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$tag_fan ($tag_fan_name)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "fan" ], "type": "tag" },
      { "params": [ "fan_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "sys_fan_rpm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "fan_rpm" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "bandwidth usage: WAN",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "rate_down" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rate_down" ], "type": "alias" }
      ],
      [
       { "params": [ "rate_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rate_up" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "$server - Fiber bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Fiber: download - rate & RX power",
   "type": "timeseries",
   "description": "Decibels (dB) is the ratio of output power to input power, expressed as 10*log (power ratio). \n\ndBm = power in decibels relative to 1mW (1000uW). A reading of 0 dBm is 1mW.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "bandwidth_down" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 8" ], "type": "math" },
       { "params": [ "Fiber: max bandwitdth" ], "type": "alias" }
      ],
      [
       { "params": [ "rate_down" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Fiber: current rate" ], "type": "alias" }
      ],
      [
       { "params": [ "sfp_pwr_rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Fiber: RX power" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Fiber: upload - rate & TX power",
   "type": "timeseries",
   "description": "Decibels (dB) is the ratio of output power to input power, expressed as 10*log (power ratio). \n\ndBm = power in decibels relative to 1mW (1000uW). A reading of 0 dBm is 1mW.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "select": [
      [
       { "params": [ "bandwidth_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 8" ], "type": "math" },
       { "params": [ "Fiber: max bandwitdth" ], "type": "alias" }
      ],
      [
       { "params": [ "rate_up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Fiber: current rate" ], "type": "alias" }
      ],
      [
       { "params": [ "sfp_pwr_tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Fiber: RX power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fiber: Maximum bandwidth rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "query": "SELECT mean(/^bandwidth_.*/) as \" \" FROM \"freebox\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "xdsl_up_maxrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "xdsl_up_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fiber: SFP statuses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox",
     "query": "SELECT min(\"sfp_alim_ok\") AS \"_sfp_alim_ok\", min(/^sfp_has_*/) AS \" \" FROM \"freebox\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sfp_alim_ok" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "sfp_alim_ok" ], "type": "alias" }
      ],
      [
       { "params": [ "sfp_has_power_report" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "sfp_has_signal" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$server - Autres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Lan browser : device count per iface",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lan_iface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "freebox_lan",
     "select": [
      [
       { "params": [ "lanhost_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "devices" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Lan browser : known devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 44 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "lan_primary_name" ], "type": "tag" },
      { "params": [ "lan_ipv4" ], "type": "tag" },
      { "params": [ "lan_ipv6" ], "type": "tag" },
      { "params": [ "lan_mac_address" ], "type": "tag" },
      { "params": [ "lan_iface" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "freebox_lan",
     "select": [
      [
       { "params": [ "lanhost_reachable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "reachable" ], "type": "alias" }
      ],
      [
       { "params": [ "lanhost_first_activity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" },
       { "params": [ "date_first_activity" ], "type": "alias" }
      ],
      [
       { "params": [ "lanhost_last_activity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" },
       { "params": [ "date_last_activity" ], "type": "alias" }
      ],
      [
       { "params": [ "lanhost_last_time_reachable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" },
       { "params": [ "date_last_time_reachable" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "Call history",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "call" ], "type": "tag" },
      { "params": [ "call_line_id" ], "type": "tag" },
      { "params": [ "call_name" ], "type": "tag" },
      { "params": [ "call_number" ], "type": "tag" },
      { "params": [ "call_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "freebox_call",
     "select": [
      [
       { "params": [ "call_datetime" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "* 1000" ], "type": "math" },
       { "params": [ "date" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "call" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "freebox_call",
     "select": [
      [
       { "params": [ "call_duration" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  { "title": "$server - switch port $switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }, "repeat": "switch" },
  {
   "title": "switch port $switch: Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "port $tag_switch_port: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "switch_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "freebox_switch",
     "select": [
      [
       { "params": [ "switch_rx_bytes_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rx_bytes_rate" ], "type": "alias" }
      ],
      [
       { "params": [ "switch_tx_bytes_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tx_bytes_rate" ], "type": "alias" }
      ],
      [
       { "params": [ "switch_collisions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "collisions" ], "type": "alias" }
      ],
      [
       { "params": [ "switch_err_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "switch_port", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "port $switch: speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "switch_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "3",
     "measurement": "freebox_switch",
     "select": [
      [
       { "params": [ "switch_speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "* 1000 * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "switch_port", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Port $switch: duplex",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "switch_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "3",
     "measurement": "freebox_switch",
     "select": [
      [
       { "params": [ "switch_duplex" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "switch_port", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  },
  {
   "title": "Port $switch: state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "switch_port" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "3",
     "measurement": "freebox_switch",
     "select": [
      [
       { "params": [ "switch_link" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$server$/" },
      { "condition": "AND", "key": "switch_port", "operator": "=~", "value": "/^$switch$/" }
     ]
    }
   ]
  }
 ]
}